/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao_bd;

import static java.lang.Integer.max;

/**
 *
 * @author Francisco Rodrigues
 */
public class consultas extends javax.swing.JFrame {

    /**
     * Creates new form consultas
     */
    public consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        textConsulta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscarButton = new javax.swing.JButton();
        opcao = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonBackCons = new javax.swing.JButton();

        jButton1.setText("Voltar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        textConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textConsulta.setToolTipText("");
        textConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConsultaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultado da Consulta");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        opcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", " " }));
        opcao.setToolTipText("");
        opcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoActionPerformed(evt);
            }
        });

        areaResultado.setColumns(20);
        areaResultado.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        areaResultado.setRows(5);
        jScrollPane1.setViewportView(areaResultado);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Biblioteca de Multimídia");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Opções de Consulta");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonBackCons.setText("Voltar");
        buttonBackCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackConsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(opcao, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(buscarButton)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBackCons))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarButton)
                            .addComponent(buttonBackCons)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConsultaActionPerformed
        System.out.println(textConsulta.getText());
    }//GEN-LAST:event_textConsultaActionPerformed

    private String[] formatTable (String[] results) {
        String[] ret = new String[1000];
        int[] colSizes = new int[1000];
        for (int lin = 0; results[lin] != null; lin++) {
            int col = 0;
            int acu = 0;
            String linhaAtual = results[lin];
            for (int i = 0; i < linhaAtual.length(); i++) {
                if (linhaAtual.charAt(i) == '\\') {
                    colSizes[col] = max (colSizes[col], acu);
                    ++col;
                    acu = 0;
                } else
                    ++acu;
            }
        }
        
        for (int lin = 0; results[lin] != null; lin++) {
            ret[lin] = "";
            int col = 0;
            int acu = 0;
            String linhaAtual = results[lin];
            for (int i = 0; i < linhaAtual.length(); i++) {
                if (linhaAtual.charAt(i) == '\\') {
                    while (acu < colSizes[col]) {
                        ret[lin] += ' ';
                        acu++;
                    }
                    ret[lin] += '|';
                    ++col;
                    acu = 0;
                } else {
                    ret[lin] += linhaAtual.charAt (i);
                    ++acu;
                }
            }
        }

        return ret;
    }
    
    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        //areaResultado.removeAll();
        int index = opcao.getSelectedIndex() + 1;
        System.out.println(index);
        String entrada = textConsulta.getText();
        System.out.println(entrada);
        String[] results = new String[100];
        consultasFunction consultar = new consultasFunction();
        try {
            consultar.chamaConexao();
        } catch (Exception ex) {
            System.out.println("Falha ao tentar conectar ao servidor");
        }
        switch (index) {
            case 1:
                try {
                    results = consultar.consulta1(entrada);
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a cosnulta");
                }
                break;
            case 2:
                try {
                    results = consultar.consulta2(entrada);
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta");
                }
                break;
            case 3:
                try {
                    results = consultar.consulta3();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta");
                }
                break;
            case 4:
                try {
                    results = consultar.consulta4();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 5:
                try {
                    results = consultar.consulta5();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 6:
                try {
                    results = consultar.consulta6();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 7:
                try {
                    results = consultar.consulta7();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 8:
                try {
                    results = consultar.consulta8();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 9:
                try {
                    results = consultar.consulta9();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 10:
                try {
                    results = consultar.consulta10();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 11:
                try {
                    results = consultar.consulta11();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 12:
                try {
                    results = consultar.consulta12();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 13:
                try {
                    results = consultar.consulta13();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 14:
                try {
                    results = consultar.consulta14(entrada);
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 15:
                try {
                    results = consultar.consulta15(entrada);
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 16:
                try {
                    results = consultar.consulta16(entrada);
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;

            case 17:
                try {
                    results = consultar.consulta17();
                } catch (Exception ex) {
                    System.out.println("Algo deu errado com a consulta.");
                }
                break;
        }
        
        results = formatTable (results);
        int i = 0;
        String imp = "";
        while (results[i] != null) {
            imp += results[i] + '\n';
            System.out.println(results[i]);
            ++i;
        }
        areaResultado.setText(imp);
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void opcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoActionPerformed

    }//GEN-LAST:event_opcaoActionPerformed

    private void buttonBackConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackConsActionPerformed
        dispose();
    }//GEN-LAST:event_buttonBackConsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton buttonBackCons;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opcao;
    private javax.swing.JTextField textConsulta;
    // End of variables declaration//GEN-END:variables
}
